data<- read.table("household_power_consumption.txt", sep=";", skip=66637, nrows = 2880)
data$V1<-paste(data$V1, data$V2)
data$V1<- strptime(data$V1, format = '%d/%m/%Y %H:%M:%S')
png(filename='plot4.png', width = 480, height = 480, units = 'px')
par(mfrow=c(2,2))
plot(data$V1, data$V3,  type='l', xlab="", ylab="Global Active Power (kilowatts)")
plot(data$V1, data$V5,  type='l', xlab="datetime", ylab="Voltage")
plot(data$V1, data$V7,  type='l', xlab="", ylab="Energy sub metering")
lines(data$V1, data$V8,  col = 'red')
lines(data$V1, data$V9,  col = 'blue')
legend('topright', c('Sub_metering_1','Sub_metering_2', 'Sub_metering_3'), lty = 1,col=c('black','red','blue'))
plot(data$V1, data$V4,  type='l', xlab="datetime", ylab="Global_reactive_power")
dev.off()